.TH leterrier-tierce 1 "November 14, 2010"
.SH NAME
leterrier\-tierce- a Tierce game
.SH SYNOPSIS
.B leterrier\-tierce
.SH DESCRIPTION
is a program which let's you playing Tierce !
.PP

leterrier\-calculette\-capricieuse (1)
.SH AUTHOR
This manual page and the script were written by Jean-Louis FRucot
<frucot.jeanlouis@free.fr>.
